### ISSUE TITLE
So this uses flatpak packages not nixplgs as nixpak?

### ISSUE THREAD

**Issue by IvanTurgenev** [alxpettit/nixpak-flatpak-wrapper#7]
Trying to understand a bit

**Comment by crabdancing** [comment]
No worries. :)

It is a facilitatory mechanism that makes it easier to use [nixpak](https://github.com/nixpak/nixpak). The complication with `nixpak` is that it works by wrapping `bwrap` and `xdg-dbus-proxy`. The ecosystem that `nixpak` has to interact with is very flatpak-centric, and as such, when the flatpak upstream needed to query something for permissions (for XDG document portal) -- they simply lazily [had it call the flatpak binary to do it](https://github.com/nixpak/nixpak/issues/62).

This is a problem because if you're installing something with `nixpak`, it may or may not have the flatpak version of anything installed at all -- and it certainly isn't good UX to have to install the `flatpak` version to get `nixpak` to work.

So, when XDG document portal tries to call the `flatpak` binary, with `nixpak-flatpak-wrapper` instead, `nixpak-flatpak-wrapper` pretends to be `flatpak` and feeds it the permissions you've set. This works in spite of the `flatpak` binary still being on your system, and there is transparent failover to have `flatpak` answer if `nixpak-flatpak-wrapper` doesn't know how to. Thus ensuring both GUI & CLI UX remains undisturbed. The goal here is to make `nixpak` more interoperable with the `flatpak` (XDG document portal) ecosystem, without having to avoid installing flatpak.

That's all `nixpak-flatpak-wrapper` does. It does not handle flatpak packages at all -- it just pretends that flatpak packages are installed when an application calls the `flatpak` binary, and reports the permissions that it was instructed to report in `/etc/nixpak-flatpak-wrapper.toml`. It is a very simple generalized solution to the basic problem as described in [upstream issue #62](https://github.com/nixpak/nixpak/issues/62).
